namespace Plugin.Maui.NativeContextMenus;

/// <summary>
/// A system icon for a <see cref="MenuNode"/>. iOS and Mac Catalyst show the SF Symbol for the value.
/// Android shows a Material Symbols icon that the package includes.
/// </summary>
public enum SystemIcon
{
    None,
    Add,
    Archive,
    Bookmark,
    Calendar,
    Call,
    Camera,
    Checkmark,
    Clock,
    Close,
    Copy,
    Cut,
    Delete,
    Download,
    Duplicate,
    Edit,
    Favorite,
    Filter,
    Flag,
    Folder,
    Heart,
    Hide,
    Info,
    Link,
    Location,
    Lock,
    Mail,
    Message,
    More,
    Open,
    Paste,
    Pause,
    Person,
    Photo,
    Pin,
    Play,
    Print,
    Refresh,
    Remove,
    Reply,
    Search,
    Send,
    Settings,
    Share,
    Show,
    Sort,
    Unlock,
}

static class SystemIconSymbols
{
    /// <summary>
    /// The SF Symbol name for a <see cref="SystemIcon"/>.
    /// </summary>
    public static string? Name(SystemIcon icon) => icon switch
    {
        SystemIcon.Add => "plus",
        SystemIcon.Archive => "archivebox",
        SystemIcon.Bookmark => "bookmark",
        SystemIcon.Calendar => "calendar",
        SystemIcon.Call => "phone",
        SystemIcon.Camera => "camera",
        SystemIcon.Checkmark => "checkmark",
        SystemIcon.Clock => "clock",
        SystemIcon.Close => "xmark",
        SystemIcon.Copy => "doc.on.doc",
        SystemIcon.Cut => "scissors",
        SystemIcon.Delete => "trash",
        SystemIcon.Download => "square.and.arrow.down",
        SystemIcon.Duplicate => "plus.square.on.square",
        SystemIcon.Edit => "pencil",
        SystemIcon.Favorite => "star",
        SystemIcon.Filter => "line.3.horizontal.decrease.circle",
        SystemIcon.Flag => "flag",
        SystemIcon.Folder => "folder",
        SystemIcon.Heart => "heart",
        SystemIcon.Hide => "eye.slash",
        SystemIcon.Info => "info.circle",
        SystemIcon.Link => "link",
        SystemIcon.Location => "location",
        SystemIcon.Lock => "lock",
        SystemIcon.Mail => "envelope",
        SystemIcon.Message => "message",
        SystemIcon.More => "ellipsis.circle",
        SystemIcon.Open => "arrow.up.forward.square",
        SystemIcon.Paste => "doc.on.clipboard",
        SystemIcon.Pause => "pause",
        SystemIcon.Person => "person",
        SystemIcon.Photo => "photo",
        SystemIcon.Pin => "pin",
        SystemIcon.Play => "play",
        SystemIcon.Print => "printer",
        SystemIcon.Refresh => "arrow.clockwise",
        SystemIcon.Remove => "minus",
        SystemIcon.Reply => "arrowshape.turn.up.left",
        SystemIcon.Search => "magnifyingglass",
        SystemIcon.Send => "paperplane",
        SystemIcon.Settings => "gearshape",
        SystemIcon.Share => "square.and.arrow.up",
        SystemIcon.Show => "eye",
        SystemIcon.Sort => "arrow.up.arrow.down",
        SystemIcon.Unlock => "lock.open",
        _ => null,
    };
}
